stages:
  - deploy
  - distrib_deploy

deploy:
  stage: deploy
  image: deploy:27
  only:
    - master
  script:
    - tooldeploy prod

distrib_deploy:
  stage: distrib_deploy
  image: deploy:36
  only:
    - master
  script:
    - distrib_deploy $CI_PROJECT_DIR -u -s
